export const PAGE_TITLE_SET = 'PAGE_TITLE_SET';
export const PAGE_CONTENT_SET = 'PAGE_CONTENT_SET';
export const NAVBAR_ITEM_SET = 'NAVBAR_ITEM_SET';
export const PREFER_ADD_ITEM = "PREFER_ADD_ITEM";
export const PREFER_REMOVE_ITEM = "PREFER_REMOVE_ITEM";
