export const PAGE_TITLE_SET = 'PAGE_TITLE_SET';
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_ACTIVITY_DETAIL = "SET_ACTIVITY_DETAIL";
export const SET_POST_DETAIL = "SET_POST_DETAIL";

//PREFER
export const PREFER_ADD_ITEM = "PREFER_ADD_ITEM";
export const PREFER_REMOVE_ITEM = "PREFER_REMOVE_ITEM";

//CART
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const EMPTY_CART = "EMPTY_CART"


export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

// REQUEST FIREBASE ACTIVITY
export const BEGIN_ACTIVITY_REQUEST = "BEGIN_ACTIVITY_REQUEST";
export const SUCCESS_ACTIVITY_REQUEST = "SUCCESS_ACTIVITY_REQUEST";
export const FAIL_ACTIVITY_REQUEST = "FAIL_ACTIVITY_REQUEST";

// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

//POSTING
export const BEGIN_POSTING = "BEGIN_POSTING";
export const SUCCESS_POSTING = "SUCCESS_POSTING";
export const RESET_POST = "RESET_POST";

export const BEGIN_COMMENT = "BEGIN_COMMENT";
export const SUCCESS_COMMENT = "SUCCESS_COMMENT";

// REQUEST FIREBASE POST
export const BEGIN_POST_REQUEST = "BEGIN_POST_REQUEST";
export const SUCCESS_POST_REQUEST = "SUCCESS_POST_REQUEST";
export const FAIL_POST_REQUEST = "FAIL_POST_REQUEST";

// CREATE ORDER
export const BEGIN_ORDER_CREATE = 'BEGIN_ORDER_CREATE';
export const SUCCESS_ORDER_CREATE = 'SUCCESS_ORDER_CREATE';
export const FAIL_ORDER_CREATE = 'FAIL_ORDER_CREATE';
export const RESET_ORDER = 'RESET_ORDER';

// GET ORDER DETAIL
export const BEGIN_ORDER_DETAIL = 'BEGIN_ORDER_DETAIL';
export const SUCCESS_ORDER_DETAIL = 'SUCCESS_ORDER_DETAIL';
export const FAIL_ORDER_DETAIL = 'FAIL_ORDER_DETAIL';

//FAVORITE
export const FAVORITE_ADD_ITEM = "FAVORITE_ADD_ITEM";
export const FAVORITE_REMOVE_ITEM = "FAVORITE_REMOVE_ITEM";